//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PUNTOVENTA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dias_permitidos
    {
        public int id { get; set; }
        public Nullable<int> dias { get; set; }
    }
}
