//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PUNTOVENTA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class puntoventaEntities1 : DbContext
    {
        public puntoventaEntities1()
            : base("name=puntoventaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<caja> caja { get; set; }
        public virtual DbSet<categoria_producto> categoria_producto { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<dias_permitidos> dias_permitidos { get; set; }
        public virtual DbSet<impuesto> impuesto { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<venta> venta { get; set; }
    }
}
