//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PUNTOVENTA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public int id { get; set; }
        public int id_categoria { get; set; }
        public int id_impuesto { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string contenido { get; set; }
        public Nullable<double> precio { get; set; }
        public int cantidad { get; set; }
        public System.DateTime creado { get; set; }
        public Nullable<System.DateTime> actualizado { get; set; }
    
        public virtual categoria_producto categoria_producto { get; set; }
        public virtual impuesto impuesto { get; set; }
    }
}
